# Generated by Django 6.0 on 2026-01-29 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_cartitem_quantity_alter_cartitem_unit_price'),
        ('store', '0002_alter_store_code_alter_store_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='one_active_cart_per_user',
        ),
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store/branch where this cart is created and checked out', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='store.store'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Snapshot price at time of adding to cart (server-controlled)', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'store'), name='one_active_cart_per_user_per_store'),
        ),
    ]
