# Generated by Django 6.0 on 2026-02-19 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_cart_one_active_cart_per_user_cart_store_and_more'),
        ('store', '0002_alter_store_code_alter_store_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store/branch context. Optional for legacy single-store carts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='store.store'),
        ),
    ]
