# Generated by Django 5.2.11 on 2026-03-09 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Fully-qualified event name (e.g. inventory.stock_adjusted)', max_length=255)),
                ('payload', models.JSONField(help_text='Serialized event payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether the event has been dispatched')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['processed'], name='event_outbo_process_8cf643_idx'), models.Index(fields=['created_at'], name='event_outbo_created_5f95ba_idx')],
            },
        ),
    ]
