# Generated by Django 6.0 on 2026-01-28 16:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_stockbatch_products_st_product_a76360_idx_and_more'),
        ('purchases', '0002_supplierpayment'),
        ('store', '0002_alter_store_code_alter_store_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='store.store'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', 'invoice_number'], name='purchases_p_supplie_d60300_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status', 'created_at'], name='purchases_p_status_964a15_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['store', 'created_at'], name='purchases_p_store_i_48dae0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceitem',
            index=models.Index(fields=['invoice', 'created_at'], name='purchases_p_invoice_f7e5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceitem',
            index=models.Index(fields=['product', 'created_at'], name='purchases_p_product_b0bcc4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='purchases_s_name_df4648_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='purchases_s_is_acti_4a355f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'created_at'], name='purchases_s_supplie_37a74b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['invoice', 'created_at'], name='purchases_s_invoice_5285fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'invoice_number'), name='uniq_supplier_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', Decimal('0.00'))), name='purchase_invoice_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='purchase_invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_invoice_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0.00'))), name='purchase_invoice_item_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'product', 'batch_number'), name='uniq_invoice_product_batchnumber'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='supplier_payment_amount_gt_zero'),
        ),
    ]
