# Generated by Django 6.0 on 2026-01-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique store/branch code (optional). If set, must be unique.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), fields=('code',), name='uniq_store_code_when_present'),
        ),
    ]
