# Generated by Django 6.0 on 2026-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
