# Generated by Django 6.0 on 2026-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_stockbatch_quantity_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='batch_number',
            field=models.CharField(help_text='Supplier / delivery batch reference', max_length=128),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_received',
            field=models.PositiveIntegerField(help_text='Quantity delivered (immutable)'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Remaining quantity (service-managed only)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('RECEIPT', 'Stock Receipt'), ('SALE', 'Sale'), ('REFUND', 'Sale Refund'), ('ADJUSTMENT', 'Manual Adjustment'), ('EXPIRY', 'Expired Stock')], max_length=20),
        ),
    ]
