# Generated by Django 6.0 on 2026-01-28 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_stockbatch_batch_number_and_more'),
        ('sales', '0002_remove_saleitem_sales_salei_sale_id_413ea3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'expiry_date'], name='products_st_product_a76360_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'is_active', 'expiry_date'], name='products_st_product_798ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='products_st_expiry__ba9211_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['created_at'], name='products_st_created_a138b2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='products_st_created_792bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reason'], name='products_st_reason_f8782e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='products_st_movemen_3c3c44_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='products_st_product_a806c1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch', 'created_at'], name='products_st_batch_i_490652_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['sale', 'created_at'], name='products_st_sale_id_c444d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt', 0)), name='chk_stockbatch_qty_received_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__gte', 0)), name='chk_stockbatch_qty_remaining_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__lte', models.F('quantity_received'))), name='chk_stockbatch_remaining_lte_received'),
        ),
    ]
