# Generated by Django 6.0 on 2026-01-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_stockbatch_products_st_product_a76360_idx_and_more'),
        ('store', '0002_alter_store_code_alter_store_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockbatch',
            name='unique_batch_per_product',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='store.store'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['store', 'created_at'], name='products_st_store_i_8c08d6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['store', 'expiry_date'], name='products_st_store_i_bfa106_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('store', 'product', 'batch_number'), name='unique_batch_per_store_product'),
        ),
    ]
