# Generated by Django 6.0 on 2026-02-01 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_stockbatch_unique_batch_per_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markup_type',
            field=models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed Amount')], default='PERCENT', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent (e.g. 20.00) if PERCENT; currency amount if FIXED.', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Unit purchase cost for this batch (immutable once set; may be null for legacy batches).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Unit cost snapshot from the referenced batch at movement time (immutable).', max_digits=12, null=True),
        ),
    ]
