# Generated by Django 6.0 on 2026-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_markup_type_product_markup_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Unit cost snapshot from batch at movement time (immutable).', max_digits=12, null=True),
        ),
    ]
