# Generated by Django 6.0 on 2026-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_stockmovement_unit_cost_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='batch_number',
            field=models.CharField(blank=True, default='', help_text='Supplier / delivery batch reference (auto-generated if blank)', max_length=128),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_received',
            field=models.PositiveIntegerField(default=1, help_text='Quantity delivered (immutable). Defaults to 1 for test compatibility.'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Remaining quantity (service-managed only). Defaults to quantity_received on create if not set.'),
        ),
    ]
