# Generated by Django 6.0 on 2026-01-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the chart (e.g. Pharmacy COA)', max_length=100, unique=True)),
                ('industry', models.CharField(help_text='Industry this chart applies to (e.g. Pharmacy, Retail)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only one chart should be active per business at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this chart was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Charts of Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='External reference (POS sale ID, refund ID, etc.)', max_length=100, null=True)),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(help_text='Accounting effective date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_posted', models.BooleanField(default=True, help_text='Locked once posted; never edited')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique account code within the chart (e.g. 1000, 4001)', max_length=10)),
                ('name', models.CharField(help_text='Human-readable account name', max_length=150)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], help_text='Accounting classification of this account', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot receive new postings')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('chart', models.ForeignKey(help_text='Chart of Accounts this account belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['code'],
                'unique_together': {('chart', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='Debit or Credit', max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive monetary value of the posting', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this ledger entry was created')),
                ('account', models.ForeignKey(help_text='Account affected by this posting', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounting.account')),
                ('journal_entry', models.ForeignKey(help_text='Parent journal entry for this ledger posting', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['created_at'],
            },
        ),
    ]
