# Generated by Django 6.0 on 2026-01-23 08:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_chartofaccounts_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-posted_at'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the journal entry was created'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(help_text='Narrative description of the journal entry'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=True, help_text='Once posted, journal entries are immutable'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Accounting effective date'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive monetary value', max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounting.journalentry'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['posted_at'], name='accounting__posted__76de1d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference'], name='accounting__referen_3e7084_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account'], name='accounting__account_a267cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['journal_entry'], name='accounting__journal_f8c821_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['created_at'], name='accounting__created_9a2302_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type'], name='accounting__entry_t_4fb8ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__isnull', False)), fields=('reference',), name='uniq_journal_reference_not_null'),
        ),
    ]
