# Generated by Django 6.0 on 2026-01-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_closes', to='accounting.chartofaccounts')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_closes', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Period Close',
                'verbose_name_plural': 'Period Closes',
                'ordering': ['-end_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('chart', 'start_date', 'end_date'), name='uniq_period_close_chart_start_end')],
            },
        ),
    ]
