# Generated by Django 6.0 on 2026-01-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_periodclose'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='periodclose',
            index=models.Index(fields=['chart', 'start_date', 'end_date'], name='accounting__chart_i_11d911_idx'),
        ),
        migrations.AddIndex(
            model_name='periodclose',
            index=models.Index(fields=['created_at'], name='accounting__created_f4f79b_idx'),
        ),
    ]
