# Generated by Django 6.0 on 2026-02-01 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_periodclose_accounting__chart_i_11d911_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-posted_at', '-created_at'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='uniq_journal_reference_not_null',
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='periodclose',
            name='journal_entry',
            field=models.ForeignKey(help_text='The journal entry that performed the close (Revenue/Expense -> Equity).', on_delete=django.db.models.deletion.PROTECT, related_name='period_closes', to='accounting.journalentry'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['chart', 'code'], name='accounting__chart_i_8cd17b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['chart', 'account_type'], name='accounting__chart_i_1aaeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_28dd04_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='accounting__expense_7b88ca_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_posted'], name='accounting__is_post_3fcb85_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_at'], name='accounting__created_b3703d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['created_at'], name='accounting__created_daff7c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted'], name='accounting__is_post_95b69a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'entry_type'], name='accounting__account_478bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['journal_entry', 'entry_type'], name='accounting__journal_6c5af3_idx'),
        ),
        migrations.AddIndex(
            model_name='periodclose',
            index=models.Index(fields=['end_date'], name='accounting__end_dat_ed219f_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('chart', 'code'), name='uniq_account_chart_code'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='chk_account_code_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chk_account_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_posted', False), ('posted_journal_entry__isnull', True)), models.Q(('is_posted', True), ('posted_journal_entry__isnull', False)), _connector='OR'), name='chk_expense_posted_requires_journal'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__isnull', False), models.Q(('reference', ''), _negated=True)), fields=('reference',), name='uniq_journal_reference_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='periodclose',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='chk_period_close_end_gte_start'),
        ),
    ]
