# Generated by Django 6.0 on 2026-02-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='business_type',
            field=models.CharField(blank=True, choices=[('pharmacy', 'Pharmacy'), ('supermarket', 'Supermarket'), ('retail', 'General Retail')], db_index=True, default=None, help_text='Business type this chart belongs to (set before activation).', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='code',
            field=models.SlugField(blank=True, default=None, help_text='Stable chart key used by resolvers/seeders. Set before go-live. Do not change after activation.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
