# Generated by Django 6.0 on 2026-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_chartofaccounts_business_type_chartofaccounts_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='business_type',
            field=models.CharField(blank=True, choices=[('pharmacy', 'Pharmacy'), ('supermarket', 'Supermarket'), ('retail', 'General Retail')], db_index=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='code',
            field=models.SlugField(blank=True, default=None, help_text='Stable chart key used by resolvers/seeders. Do not change after go-live.', max_length=64, null=True, unique=True),
        ),
    ]
