# Generated by Django 6.0 on 2026-02-14 12:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_chartofaccounts_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive monetary value', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
