# Generated by Django 5.2.11 on 2026-03-08 11:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_ledgerentry_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_manual_posting',
            field=models.BooleanField(default=True, help_text='If False, only system modules may post here'),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_control_account',
            field=models.BooleanField(default=False, help_text='Control accounts cannot receive manual journal postings'),
        ),
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', help_text='Expected accounting balance direction', max_length=6),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='system_account',
            field=models.BooleanField(default=False, help_text='System accounts cannot be deleted or modified'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(default='system', help_text='Originating module (POS, Refunds, Expenses, Inventory, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('COGS', 'Cost of Goods Sold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
