# Generated by Django 5.2.11 on 2026-03-08 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_expense_created_by_expense_store_and_more'),
        ('store', '0002_alter_store_code_alter_store_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('sale_completed', 'Sale Completed'), ('refund_issued', 'Refund Issued'), ('expense_recorded', 'Expense Recorded'), ('inventory_adjustment', 'Inventory Adjustment')], db_index=True, max_length=50)),
                ('source_model', models.CharField(help_text='Model name that generated the event (Sale, RefundAudit, Expense, etc.)', max_length=100)),
                ('source_id', models.UUIDField(db_index=True, help_text='Primary key of the originating object')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, help_text='Processing error if event failed', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounting_events', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_events', to='store.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='accounting__event_t_3c92d2_idx'), models.Index(fields=['processing_status'], name='accounting__process_b31f68_idx'), models.Index(fields=['source_model', 'source_id'], name='accounting__source__b21de5_idx'), models.Index(fields=['store', 'created_at'], name='accounting__store_i_e0f55f_idx')],
            },
        ),
    ]
