# Generated by Django 6.0 on 2026-01-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_stockbatch_batch_number_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_salei_sale_id_413ea3_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_salei_product_f87493_idx',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='batch_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salerefundaudit',
            name='original_total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total sale amount at time of refund', max_digits=12),
        ),
    ]
