# Generated by Django 6.0 on 2026-01-31 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_stockbatch_unique_batch_per_product_and_more'),
        ('sales', '0002_remove_saleitem_sales_salei_sale_id_413ea3_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='saleitem',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'created_at'], name='sales_salei_sale_id_d1ee2d_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product', 'created_at'], name='sales_salei_product_882dd0_idx'),
        ),
    ]
