# Generated by Django 6.0 on 2026-02-01 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_options_saleitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Cost of Goods Sold for this sale (FIFO-derived).', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='gross_profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit = subtotal_amount - cogs_amount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost for this line (snapshot).', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gross_profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line gross profit = total_price - cost_amount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='FIFO-derived unit cost at time of sale (snapshot).', max_digits=12),
        ),
        migrations.AddField(
            model_name='salerefundaudit',
            name='original_cogs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='COGS at time of refund (snapshot for deterministic reversal).', max_digits=12),
        ),
        migrations.AddField(
            model_name='salerefundaudit',
            name='original_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount at time of refund (snapshot).', max_digits=12),
        ),
        migrations.AddField(
            model_name='salerefundaudit',
            name='original_gross_profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit at time of refund (snapshot).', max_digits=12),
        ),
        migrations.AddField(
            model_name='salerefundaudit',
            name='original_subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal at time of refund (snapshot).', max_digits=12),
        ),
        migrations.AddField(
            model_name='salerefundaudit',
            name='original_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax at time of refund (snapshot).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salerefundaudit',
            name='original_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total at time of refund (snapshot).', max_digits=12),
        ),
    ]
