# Generated by Django 6.0 on 2026-02-06 11:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_cogs_amount_sale_gross_profit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='cash', help_text='cash/bank/pos/transfer/credit/split', max_length=32),
        ),
        migrations.CreateModel(
            name='SalePaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('pos', 'POS'), ('transfer', 'Transfer'), ('credit', 'Credit')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='sales.sale')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sale'], name='sales_salep_sale_id_dd1d88_idx'), models.Index(fields=['method'], name='sales_salep_method_a632f6_idx'), models.Index(fields=['created_at'], name='sales_salep_created_f1721a_idx')],
            },
        ),
    ]
