# Generated by Django 6.0 on 2026-02-14 10:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_stockmovement_unit_cost_snapshot'),
        ('sales', '0006_saleitemrefund'),
        ('store', '0002_alter_store_code_alter_store_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(blank=True, help_text='System-generated public order number', max_length=64, unique=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=40)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending_payment', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='quantity * unit_price (server computed)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=32)),
                ('reference', models.CharField(help_text='Provider reference (Paystack reference). Must be unique for idempotency.', max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('redirected', 'Redirected'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=32)),
                ('authorization_url', models.URLField(blank=True, default='')),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='saleitemrefund',
            new_name='sales_salei_sale_id_0300e4_idx',
            old_name='sales_saleit_sale_id_9c3a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitemrefund',
            new_name='sales_salei_sale_it_132020_idx',
            old_name='sales_saleit_sale_it_5b2e2c_idx',
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_online_order', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_orders', to='store.store'),
        ),
        migrations.AddField(
            model_name='onlineorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.onlineorder'),
        ),
        migrations.AddField(
            model_name='onlineorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_order_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='sales.onlineorder'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['created_at'], name='sales_onlin_created_a2fc57_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['status'], name='sales_onlin_status_37aee0_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['order_no'], name='sales_onlin_order_n_260acf_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['store', 'created_at'], name='sales_onlin_store_i_8dbeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['store', 'status'], name='sales_onlin_store_i_f429f5_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorderitem',
            index=models.Index(fields=['created_at'], name='sales_onlin_created_fb8aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorderitem',
            index=models.Index(fields=['order'], name='sales_onlin_order_i_2e68b8_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorderitem',
            index=models.Index(fields=['product'], name='sales_onlin_product_afbce3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['initiated_at'], name='sales_payme_initiat_8796d7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['status'], name='sales_payme_status_24038e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider'], name='sales_payme_provide_b97f65_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['reference'], name='sales_payme_referen_e6334e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['order', 'initiated_at'], name='sales_payme_order_i_7c231d_idx'),
        ),
    ]
