# Generated by Django 5.2.11 on 2026-03-01 21:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_salerefundaudit_original_cogs_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_created_e208b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_status_532843_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_invoice_5ca049_idx',
        ),
        migrations.RenameField(
            model_name='salerefundaudit',
            old_name='original_cogs_amount',
            new_name='cogs_amount',
        ),
        migrations.RenameField(
            model_name='salerefundaudit',
            old_name='original_discount_amount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='salerefundaudit',
            old_name='original_gross_profit_amount',
            new_name='gross_profit_amount',
        ),
        migrations.RenameField(
            model_name='salerefundaudit',
            old_name='original_subtotal_amount',
            new_name='subtotal_amount',
        ),
        migrations.RenameField(
            model_name='salerefundaudit',
            old_name='original_tax_amount',
            new_name='tax_amount',
        ),
        migrations.RenameField(
            model_name='salerefundaudit',
            old_name='original_total_amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='salerefundaudit',
            name='is_accounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gross_profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='cash', max_length=32),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salerefundaudit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salerefundaudit',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_audits', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='salerefundaudit',
            index=models.Index(fields=['sale'], name='sales_saler_sale_id_190aea_idx'),
        ),
        migrations.AddIndex(
            model_name='salerefundaudit',
            index=models.Index(fields=['refunded_at'], name='sales_saler_refunde_998d1b_idx'),
        ),
    ]
