# Generated by Django 5.2.11 on 2026-03-08 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_sale_sales_sale_created_e208b3_idx_and_more'),
        ('store', '0002_alter_store_code_alter_store_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store.store'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'created_at'], name='sales_sale_store_i_e6f7be_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_sale_status_532843_idx'),
        ),
    ]
