# Generated by Django 6.0 on 2026-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('reception', 'Reception'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
