# Generated by Django 6.0 on 2026-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username_user_users_user_usernam_65d164_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_usernam_65d164_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
